// "use client";
import React from "react";
import Event from "./Event";

export async function generateMetadata({ params }) {
  const id = params.id;
  const res = await fetch("https://next-events-pi-sandy.vercel.app/api/events");
  const allEvents = await res.json();

  const data = allEvents.find((item) => item.id === id);
  return {
    title: `HotEvents - ${data.title}`,
    description: "Generated by create next app",
  };
}

export default async function page() {
  return (
    <div>
      <Event />
    </div>
  );
}
