// "use client";
import React from "react";
import Event from "./Event";

export async function generateMetadata({ params }) {
  const id = params.id;
  // https://next-events-hyppouicf-karin210.vercel.app/api/events
  const res = await fetch("http://localhost:3000/api/events", {
    next: { revalidate: 60 },
  });
  const allEvents = await res.json();

  const data = allEvents.find((item) => item.id === id);
  return {
    title: `HotEvents - ${data.title}`,
    // title: "Id",
    description: "Generated by create next app",
  };
}

export default async function page() {
  // const res = await fetch("http://localhost:3000/api/events");
  // const allEvents = await res.json();
  // console.log(allEvents);
  return (
    <div>
      <Event />
    </div>
  );
}
